name: TQQQ_Daily_Alert

on:
  schedule:
    - cron: '0 23 * * *' # 한국 시간 기준 매일 오전 8시 (UTC 23:00)
  workflow_dispatch: # 수동으로 실행해볼 수 있는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # '3.9'에서 '3.12'로 변경하세요!

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas_ta requests pandas

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
